modLoader = "javafml"
loaderVersion = "[36,)"
license = "Public domain"
issueTrackerURL = "" 
[[mods]] 
  modId = "plusutils"
  version = "1.20.1-0.0.1"
  displayName = "PlusUtils"
  updateJSONURL="" 
  displayURL = "https://discord.gg/wWdXpwuPmK" 
  authors = "iDark"
  description = '''
  bunch of utils
'''
    [[dependencies.plusutils]]
  modId = "forge"
  mandatory = true
  versionRange = "[36,)"
  ordering = "NONE"
  side = "BOTH"
    [[dependencies.plusutils]]
		modId = "minecraft"
		mandatory = true
		versionRange = "[1.20.1,1.21)"
		ordering = "NONE"
		side = "BOTH"
